server:
  port: 8443
  ssl:
    key-store: mykeys.jks
    key-store-password: 111111
    key-password: 111111
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taco_cloud
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      hbm2ddl:
        auto: none
  thymeleaf:
    cache: false
